// Generated by scripts/generate-noor-contract.js from docs/contracts/noor-rag-v1.schema.json.
// Do not edit this file directly.

export type NoorSource = "ibn_kathir_en_abridged" | "al_sadi_ar";

export type NoorHistoryRole = "user" | "assistant";

export type RequestId = string;

export type Question = string;

export type QuranSurah = number;

export type QuranVerse = number;

export interface NoorHistoryTurn {
    role: NoorHistoryRole;
    content: string;
}

export interface NoorVerseContext {
    surah: QuranSurah;
    verse: QuranVerse;
}

export interface NoorChatRequest {
    mode: "chat";
    requestId: RequestId;
    question: Question;
    history: Array<NoorHistoryTurn>;
    verseContext?: NoorVerseContext;
}

export interface NoorVerseSummaryRequest {
    mode: "verse_summary";
    requestId: RequestId;
    source: NoorSource;
    surah: QuranSurah;
    verse: QuranVerse;
}

export interface NoorVerseQuestionRequest {
    mode: "verse_question";
    requestId: RequestId;
    source: NoorSource;
    surah: QuranSurah;
    verse: QuranVerse;
    question: Question;
}

export type NoorRequest = NoorChatRequest | NoorVerseSummaryRequest | NoorVerseQuestionRequest;

export type NoorStatus = "answered" | "insufficient_evidence" | "policy_refusal" | "not_entitled" | "quota_exceeded" | "invalid_request" | "temporarily_unavailable";

export interface NoorCitation {
    chunkId: string;
    canonicalUnitId: string;
    source: NoorSource;
    sourceTitle: string;
    surah: QuranSurah;
    verseStart: QuranVerse;
    verseEnd: QuranVerse;
    corpusVersion: string;
}

export interface NoorQuotaExceededAnswer {
    requestId: RequestId;
    answer: string;
    status: "quota_exceeded";
    citations: Array<NoorCitation>;
    nextResetAt: string;
}

export interface NoorNonQuotaAnswer {
    requestId: RequestId;
    answer: string;
    status: "answered" | "insufficient_evidence" | "policy_refusal" | "not_entitled" | "invalid_request" | "temporarily_unavailable";
    citations: Array<NoorCitation>;
    nextResetAt?: never;
}

export type NoorAnswer = NoorQuotaExceededAnswer | NoorNonQuotaAnswer;
